import { db, auth, collection, addDoc, doc, updateDoc, query, orderBy, onSnapshot, serverTimestamp, signInWithEmailAndPassword, onAuthStateChanged, signOut, slugify, cleanEmbed, subscribeAllCourses, escapeHTML } from './app.js';
const $ = (id) => document.getElementById(id); const loginView=$('loginView'), workspace=$('workspace'); let selectedCourse = null;
$('loginForm').addEventListener('submit', async (event) => { event.preventDefault(); $('loginMessage').textContent='Signing in…'; try { await signInWithEmailAndPassword(auth, $('email').value.trim(), $('password').value); $('loginMessage').textContent=''; } catch (error) { $('loginMessage').textContent='Sign-in failed. Check your email and password.'; } });
$('logoutButton').addEventListener('click', () => signOut(auth));
onAuthStateChanged(auth, (user) => { loginView.hidden=!!user; workspace.hidden=!user; if (user) subscribeAllCourses((snapshot) => { const courses=snapshot.docs.map((item)=>({id:item.id,...item.data()})); $('courseSelect').innerHTML='<option value="">Select a course</option>'+courses.map((course)=>`<option value="${escapeHTML(course.id)}">${escapeHTML(course.title)} · ${escapeHTML(course.status)}</option>`).join(''); $('courseList').innerHTML=courses.map((course)=>`<button class="admin-list-item" data-course="${escapeHTML(course.id)}"><strong>${escapeHTML(course.title)}</strong><span>${escapeHTML(course.status)}</span></button>`).join(''); document.querySelectorAll('[data-course]').forEach((button)=>button.addEventListener('click',()=>loadCourse(courses.find((course)=>course.id===button.dataset.course)))); }, () => $('courseMessage').textContent='Could not load courses.'); });
function loadCourse(course) { selectedCourse=course; $('courseDocId').value=course.id; $('courseTitle').value=course.title||''; $('courseId').value=course.courseId||''; $('courseCategory').value=course.category||''; $('thumbnailUrl').value=course.thumbnailUrl||''; $('courseDescription').value=course.description||''; $('courseStatus').value=course.status||'in_development'; $('courseSelect').value=course.id; }
$('courseSelect').addEventListener('change',(event)=>{ if(event.target.value) document.querySelector(`[data-course="${CSS.escape(event.target.value)}"]`)?.click(); });
$('courseForm').addEventListener('submit', async (event)=>{ event.preventDefault(); const payload={title:$('courseTitle').value.trim(),courseId:slugify($('courseId').value),category:$('courseCategory').value.trim(),thumbnailUrl:$('thumbnailUrl').value.trim(),description:$('courseDescription').value.trim(),status:$('courseStatus').value,updatedAt:serverTimestamp()}; try { if($('courseDocId').value) await updateDoc(doc(db,'courses',$('courseDocId').value),payload); else await addDoc(collection(db,'courses'),{...payload,createdAt:serverTimestamp()}); $('courseMessage').textContent='Course saved.'; } catch(error) { $('courseMessage').textContent='Could not save course.'; } });
$('postForm').addEventListener('submit', async (event)=>{ event.preventDefault(); if(!selectedCourse) { $('postMessage').textContent='Select a course first.'; return; } try { const iframe=cleanEmbed($('videoIframe').value); await addDoc(collection(db,'posts'),{courseId:selectedCourse.id,title:$('postTitle').value.trim(),slug:slugify($('postTitle').value),videoIframe:iframe,content:$('postContent').value.trim(),author:$('postAuthor').value.trim(),publishedAt:serverTimestamp()}); if(selectedCourse.status==='in_development') await updateDoc(doc(db,'courses',selectedCourse.id),{status:'published',updatedAt:serverTimestamp()}); $('postMessage').textContent='Post published and course is live.'; event.target.reset(); } catch(error) { $('postMessage').textContent=error.message||'Could not publish post.'; } });
